### ISSUE TITLE
Wiki feedback

### ISSUE THREAD

**Issue by akondrahman** [RealsearchGroup/StudentWiki#1]
My feedback on the [Wiki](https://github.com/RealsearchGroup/StudentWiki/wiki/Realsearch-Requirements-for-Structuring-a-Research-Paper) 

- Also, see Mary Shaw's "Writing Good Software Engineering Papers" for writing an abstract. 
> This is pretty old ... the community has evolved since 2003 

- Many people people write the abstract last. It will generally write itself after the paper is done.
> Many people write the abstract last. It will generally write itself after the paper is done.

- Can add following about abstract 
> An abstract is a brief but sharp summary of the whole paper. The flow of the abstract is:
Context -> Problem -> Goal -> Methodology -> Results -> Conclusion 

- For methodology you can add
> Organize the section based on your research questions 

- For limitations section can add
> Organize this section as following: construct validity, conclusion validity, internal validity, and external validity. What content will go to each subsection will be based on the criteria mentioned in 'Experimentation in Software Engineering' book. 

- For general principles you can add: 
> Always remember you cannot write a scientific paper in the same manner you talk; because it is scientific writing, each word you write matters.

**Comment by seelder** [comment]
I think I've updated most of these. Will keep looking for a good replacement to the Shaw paper. I like the [4-sentence abstract paper](https://plg.uwaterloo.ca/~migod/research/beckOOPSLA.html) as a starting point, but especially with our goal statement the abstract usually ends up being more than 4 sentences.

**Comment by seelder** [comment]
Shaw issue merged with #9. I THINK the rest of these were addressed in one way or another
